/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class buy_beverages extends javax.swing.JFrame {

    /**
     * Creates new form buychicken
     */
    public buy_beverages() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 680, 300, 30);

        jButton1.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jButton1.setText("order now ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 610, 170, 40);

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel2.setText("redbull");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 300, 230, 30);

        jTextField1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 300, 110, 30);

        jTextField2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(290, 130, 110, 30);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel3.setText("pepsi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 130, 230, 30);

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel4.setText("mirinda");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 130, 230, 30);

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel5.setText("7up");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 210, 230, 30);

        jTextField4.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(290, 210, 110, 30);

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel6.setText("mountain dew");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(550, 210, 230, 30);

        jTextField5.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(730, 210, 110, 30);

        jLabel7.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel7.setText("mango shake");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 300, 230, 30);

        jTextField6.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(730, 300, 110, 30);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel8.setText("cappuccino");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 380, 230, 30);

        jTextField7.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField7);
        jTextField7.setBounds(290, 380, 110, 30);

        jLabel9.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel9.setText("latte");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 380, 230, 30);

        jTextField8.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(730, 380, 110, 30);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Your Order");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 30, 340, 60);

        jTextField3.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(730, 130, 110, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1310, 10, 30, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sweethome.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1270, 10, 30, 30);

        jLabel12.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel12.setText("americano");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(110, 460, 230, 30);

        jTextField9.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField9);
        jTextField9.setBounds(290, 460, 110, 30);

        jTextField10.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField10);
        jTextField10.setBounds(730, 460, 110, 30);

        jLabel13.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel13.setText("chocolate shake");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(550, 460, 230, 30);

        jTextField11.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField11);
        jTextField11.setBounds(290, 540, 110, 30);

        jLabel14.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel14.setText("currant shake");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(110, 540, 230, 30);

        jTextField12.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField12);
        jTextField12.setBounds(730, 540, 110, 30);

        jLabel15.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel15.setText("cookie shake");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(550, 540, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1357, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        beansn_cream b=new beansn_cream();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = 100, b = 100, c = 120, d = 120, e = 180, f = 60, g = 150, h = 50, i=70, j=150, k=150, l=200 ;
        int af, bf, cf, df, ef, ff, gf, hf, iff, jf, kf, lf;
//        if(jTextField2.getText() == null) af =0;
        String temp;
//        temp = jTextField2.getText();
        if(jTextField2.getText().isEmpty()) af =0;
        else af = Integer.parseInt(jTextField2.getText());
        if(jTextField3.getText().isEmpty()) bf =0;
        else bf = Integer.parseInt(jTextField3.getText());
        if(jTextField4.getText().isEmpty()) cf =0;
        else cf = Integer.parseInt(jTextField4.getText());
        if(jTextField5.getText().isEmpty()) df =0;
        else df = Integer.parseInt(jTextField5.getText());
        if(jTextField1.getText().isEmpty()) ef =0;
        else ef = Integer.parseInt(jTextField1.getText());
        if(jTextField6.getText().isEmpty()) ff =0;
        else ff = Integer.parseInt(jTextField6.getText());
        if(jTextField7.getText().isEmpty()) gf =0;
        else gf = Integer.parseInt(jTextField7.getText());
        if(jTextField8.getText().isEmpty()) hf =0;
        else hf = Integer.parseInt(jTextField8.getText());
        if(jTextField9.getText().isEmpty()) iff =0;
        else iff = Integer.parseInt(jTextField9.getText());
        if(jTextField10.getText().isEmpty()) jf =0;
        else jf = Integer.parseInt(jTextField10.getText());
        if(jTextField11.getText().isEmpty()) kf =0;
        else kf = Integer.parseInt(jTextField11.getText());
        if(jTextField12.getText().isEmpty()) lf =0;
        else lf = Integer.parseInt(jTextField12.getText());
        
        int total = a*af + b*bf + c*cf + d*df + e*ef + f*ff + g*gf + h * hf + i*iff + j*jf + k*kf + l*lf;
//        if(jTextField2.getText() == null ) 
//        jLabel3.setText(""+total);
        jLabel11.setText("Total Amount : " + total);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buychicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buychicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buychicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buychicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buychicken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
